/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#95d3ba',
        'primary-fixed': '#b0f0d6',
        'on-primary-container': '#80bea6',
        'surface-dim': '#dbdad7',
        'on-primary': '#ffffff',
        'primary': '#003527',
        'surface-container-low': '#f4f3f1',
        'tertiary-fixed-dim': '#ffb77d',
        'surface-container': '#efeeeb',
        'on-tertiary': '#ffffff',
        'surface': '#faf9f6',
        'surface-tint': '#2b6954',
        'on-secondary': '#ffffff',
        'background': '#faf9f6',
        'primary-fixed-dim': '#95d3ba',
        'surface-bright': '#faf9f6',
        'secondary-container': '#dae2fd',
        'secondary-fixed': '#dae2fd',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#131b2e',
        'tertiary': '#4a2400',
        'surface-container-highest': '#e3e2e0',
        'secondary-fixed-dim': '#bec6e0',
        'on-surface': '#1a1c1a',
        'on-background': '#1a1c1a',
        'on-tertiary-fixed': '#2f1500',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#064e3b',
        'on-tertiary-fixed-variant': '#6e3900',
        'surface-container-high': '#e9e8e5',
        'tertiary-fixed': '#ffdcc3',
        'on-primary-fixed': '#002117',
        'inverse-on-surface': '#f2f1ee',
        'on-error-container': '#93000a',
        'on-secondary-container': '#5c647a',
        'on-primary-fixed-variant': '#0b513d',
        'secondary': '#565e74',
        'error': '#ba1a1a',
        'outline': '#707974',
        'surface-variant': '#e3e2e0',
        'on-error': '#ffffff',
        'outline-variant': '#bfc9c3',
        'on-surface-variant': '#404944',
        'tertiary-container': '#6a3700',
      },
      spacing: {
        'sidebar-width': '17.5rem',
        'space-xs': '0.5rem',
        'space-xl': '2rem',
        'space-2xs': '0.25rem',
        'space-3xs': '0.125rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      fontSize: {
        'headline-xl': '1.75rem',
        'headline-lg': '1.5rem',
        'headline-sm': '1.25rem',
        'body-md': '1rem',
        'body-sm': '0.875rem',
        'label-sm': '0.75rem',
        'caption-caps': '0.6875rem',
      },
      fontFamily: {
        'sans': ['Plus Jakarta Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
